### ISSUE TITLE
Add support for making histograms from R

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/ACRO#171] opened 2023-10-10 15:12 UTC
Add functionality to support images generated from plots such as histograms - I think this involves modifying the records module so that there is another function that will record the path to the generated plot, plus the status summary (pass, fail, review, etc.) and then a list of strings which contain details from the checks that give the reason for the status.

**Comment by jim-smith** [comment] 2023-10-13 07:33
Duplicate of #70 

Modifying the r records module is the major part.

Calculating the risk for something created via pd.DataFrame.hist() is actually faulty straightforward:
- takres a parameter ```bins``` which is either an int or a list of bin edges
- that is passed straight through to plt.hist, which ion turn passes it through to numpy.hist() 
- numpy returns an array (or maybe a list) of frequency counts

**Comment by jim-smith** [comment] 2023-10-20 09:53
Main thing is to map the parameters. for R syntax through to pandas syntax to call there acro function

**Closed** 2023-10-31 13:24 UTC
